// ═══════════════════════════════════════════════════════════════
// CONFIGURATION FILE — edit this file to customize your bot
// ═══════════════════════════════════════════════════════════════

module.exports = {

  // ─────────────────────────────────────────────
  // PACKAGES
  // price is in Telegram Stars (XTR)
  // videos = expected count; actual content = packageContent below
  // ─────────────────────────────────────────────
  packages: {
    A: {
      id: 'A',
      name: '📚 Paket Starter',
      price: 100,
      description: '10 Video Tutorial\n✅ Akses seumur hidup\n✅ Update gratis',
      videos: 10
    },
    B: {
      id: 'B',
      name: '🎓 Paket Professional',
      price: 200,
      description: '25 Video Pro\n✅ Mentoring eksklusif\n✅ Garansi channel',
      videos: 25
    },
    C: {
      id: 'C',
      name: '👑 Paket Premium',
      price: 400,
      description: '50+ Video Premium\n✅ Priority support\n✅ Sertifikat digital',
      videos: 50
    },
    D: {
      id: 'D',
      name: '💡 Paket Basic',
      price: 72,
      description: '5 Video Dasar\n✅ Akses 1 bulan\n✅ Refresh gratis',
      videos: 5
    },
    E: {
      id: 'E',
      name: '🚀 Paket Growth',
      price: 130,
      description: '15 Video Growth\n✅ Mentoring grup\n✅ Update mingguan',
      videos: 15
    },
    F: {
      id: 'F',
      name: '💎 Paket Master',
      price: 300,
      description: '40+ Video Master\n✅ Akses unlimited\n✅ Lifetime support',
      videos: 40
    }
  },

  // ─────────────────────────────────────────────
  // CONTENT MAPPING
  // Map each package to Message IDs inside sourceGroupId.
  // To add content: upload video to source group → copy message ID → add here.
  // To remove: delete the ID from the list. No re-upload needed.
  // ─────────────────────────────────────────────
  packageContent: {
    A: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    B: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25],
    C: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
    D: [1, 2, 3, 4, 5],
    E: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    F: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
  },

  // ─────────────────────────────────────────────
  // CREATOR ACCOUNTS
  // Each account needs:
  //   apiId / apiHash  → from https://my.telegram.org
  //   phoneNumber      → international format
  //   sessionString    → generated by running the login script once
  //   active           → toggle without removing
  //   limitReached     → managed at runtime; set false on restart
  //
  // Add more accounts to enable auto-failover when one hits
  // Telegram's channel creation rate limit.
  // ─────────────────────────────────────────────
  creatorAccounts: [
    {
      id: 1,
      apiId: parseInt(process.env.API_ID_1),
      apiHash: process.env.API_HASH_1,
      phoneNumber: process.env.PHONE_1 || '+62812345678',
      sessionString: process.env.SESSION_1 || '',
      active: true,
      limitReached: false
    },
    // Example second account — add real values in .env:
    // {
    //   id: 2,
    //   apiId: parseInt(process.env.API_ID_2),
    //   apiHash: process.env.API_HASH_2,
    //   phoneNumber: process.env.PHONE_2 || '+62887654321',
    //   sessionString: process.env.SESSION_2 || '',
    //   active: true,
    //   limitReached: false
    // }
  ],

  // ─────────────────────────────────────────────
  // SOURCE GROUP
  // The Telegram group/channel where all master videos are stored.
  // Bot's creator accounts must be members of this group.
  // Format: -100xxxxxxxxxx (supergroup) or @username
  // ─────────────────────────────────────────────
  sourceGroupId: parseInt(process.env.SOURCE_GROUP_ID) || -1001234567890,

  // ─────────────────────────────────────────────
  // ADMIN
  // Telegram user ID of the bot admin (use @userinfobot to find yours)
  // ─────────────────────────────────────────────
  adminId: process.env.ADMIN_ID,

  // ─────────────────────────────────────────────
  // WARRANTY SETTINGS
  // ─────────────────────────────────────────────
  maxWarrantyPerPurchase: 1   // users can claim warranty once per purchase
};
